stages:
  - test

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: test
  script:
    - npm run lint

prettier:
  stage: test
  script:
    - npm run check:format