stages:
  - test

eslint:
  stage: test
  variables:
    NODE_VERSION: 14.17.0
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - eval "[ -f .nvmrc ] && nvm install"
    - npm install
    - npm run lint

prettier:
  image: node:14.17.0-alpine
  stage: test
  script:
    - npm install
    - npm run check:format
