name: Caching with npm
on: 
  push:
    branches: [main1]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm install
  eslint:
      needs: build
      name: ESLint cache
      runs-on: ubuntu-latest
      container:
        image: node:14.17.0-alpine
      steps:
        - uses: actions/checkout@v3
        - name: Cache node modules
          id: cache-npm
        - name: Cache dependencies
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: .npm
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Lint source code with ESLint
          run: npm run lint